settings:
  title: 'Status Page'
  url: 'https://stat.imki.moe' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  # - id: workers-cloudflare-com # unique identifier
  #   name: workers.cloudflare.com
  #   description: 'You write code. They handle the rest.' # default=empty
  #   url: 'https://workers.cloudflare.com/' # URL to fetch
  #   method: GET # default=GET
  #   expectStatus: 200 # operational status, default=200
  #   followRedirect: false # should fetch follow redirects, default=false
  #   linkable: false # allows the title to be a link, default=true

  - id: imki-moe
    name: imki.moe | Home
    description: 'The Index'
    url: 'https://imki.moe/'
    method: GET
    expectStatus: 200
  
  - id: blog-imki-moe
    name: blog.imki.moe | Blog
    description: 'The Blog'
    url: 'https://blog.imki.moe/'
    method: GET
    expectStatus: 200
  
  - id: api-imki-moe
    name: api.imki.moe | HibiAPI Service
    description: 'HibiAPI Service. If it is down, please contact me: 0w0@imki.moe'
    url: 'https://api.imki.moe/docs'
    method: GET
    expectStatus: 200
  
  - id: drive-imki-moe
    name: drive.imki.moe | File Sharing
    description: 'Resource site'
    url: 'https://drive.imki.moe/'
    method: GET
    expectStatus: 200
